### ISSUE TITLE
failed installation of cookiecutter on Ubuntu 20.04/python 3.8

### ISSUE THREAD

**Issue by blaufuss** [scimma/hop-app-template#6]
Issue from the Scimma hopskotch demo

When trying to install cookiecutter:

(env3) blaufuss@ubu[scimma]% pip install cookiecutter
Collecting cookiecutter
  Downloading cookiecutter-1.7.2-py2.py3-none-any.whl (34 kB)
Collecting binaryornot>=0.4.4
  Downloading binaryornot-0.4.4-py2.py3-none-any.whl (9.0 kB)
Collecting Jinja2<3.0.0
  Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 4.7 MB/s
Collecting python-slugify>=4.0.0
  Downloading python-slugify-4.0.0.tar.gz (8.8 kB)
Collecting click>=7.0
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 2.0 MB/s
Collecting MarkupSafe<2.0.0
  Downloading MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl (32 kB)
Collecting six>=1.10
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting jinja2-time>=0.2.0
  Downloading jinja2_time-0.2.0-py2.py3-none-any.whl (6.4 kB)
Collecting poyo>=0.5.0
  Downloading poyo-0.5.0-py2.py3-none-any.whl (10 kB)
Collecting requests>=2.23.0
  Downloading requests-2.23.0-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 4.0 MB/s
Collecting chardet>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 6.5 MB/s
Collecting text-unidecode>=1.3
  Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 4.8 MB/s
Collecting arrow
  Downloading arrow-0.15.6-py2.py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 4.7 MB/s
Requirement already satisfied: certifi>=2017.4.17 in ./env3/lib/python3.8/site-packages (from requests>=2.23.0->cookiecutter) (2020.4.5.1)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
     |████████████████████████████████| 126 kB 7.3 MB/s
Collecting idna<3,>=2.5
  Downloading idna-2.9-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 4.7 MB/s
Collecting python-dateutil
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 7.1 MB/s
Building wheels for collected packages: python-slugify
  Building wheel for python-slugify (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/blaufuss/scimma/env3/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-es5kou9c/python-slugify/setup.py'"'"'; __file__='"'"'/tmp/pip-install-es5kou9c/python-slugify/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-uj17vlbr
       cwd: /tmp/pip-install-es5kou9c/python-slugify/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for python-slugify
  Running setup.py clean for python-slugify
Failed to build python-slugify
Installing collected packages: chardet, binaryornot, MarkupSafe, Jinja2, text-unidecode, python-slugify, click, six, python-dateutil, arrow, jinja2-time, poyo, urllib3, idna, requests, cookiecutter
    Running setup.py install for python-slugify ... done
Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 arrow-0.15.6 binaryornot-0.4.4 chardet-3.0.4 click-7.1.2 cookiecutter-1.7.2 idna-2.9 jinja2-time-0.2.0 poyo-0.5.0 python-dateutil-2.8.1 python-slugify-4.0.0 requests-2.23.0 six-1.15.0 text-unidecode-1.3 urllib3-1.25.9

thanks

**Comment by myNameIsPatrick** [comment]
@blaufuss, it seems like during the installation of `cookiecutter`, it is trying to pull the `python-slugify` package as a tarball and creating a python wheel on the fly. The error message you're seeing is because `wheel` is not installed, I believe. I'm not sure why pip is getting itself into this situation in the first place, but this may be solved by doing the following before installing `cookiecutter`:

`pip install wheel`

**Comment by blaufuss** [comment]
confirmed, installing 'wheel' before cookiecutter in the venv solves this issue.  
Is this a missing dependency of something  in  the dep chain?  Thanks
